'''
PROPOSTA DO DESAFIO: ACESSAR PÁGINA DO DESAFIO 4 QUE SIMULA UMA PÁGINA DE E-COMMERCE, QUE POSSUI DIVERSAS OPÇÕES DE FILTRO PARA MOSTRAR OS PRODUTOS.
A AUTOMAÇÃO DEVERÁ:
- SELECIONAR TODOS OS PRODUTOS DA CATEGORIA CELULARES COM FRETE GRÁTIS, EM OFERTA, PREÇO ENTRE R$ 500,00 - R$ 2.500,00 E COM 4 ESTRELAS DE AVALIAÇÃO
- SELECIONAR TODOS OS PRODUTOS DA CATEGORIA TVS COM ENVIO INTERNACIONAL, PREÇO ATÉ R$ 5.000,00 E 5 ESTRELAS
- SELECIONAR TODOS OS PRODUTOS DA CATEGORIA GAMES COM PARCELAMENTO SEM JUROS, FRETE GRÁTIS, PREÇO ENTRE R$ 2.000,00 E R$ 8.000,00 E 3 ESTRELAS
- SELECIONAR TODOS OS PRODUTOS DA CATEGORIA NOTEBOOKS COM PARCELAMENTO SEM JUROS, EM OFERTA, PREÇO ENTRE R$ 1.234,00 E R$ 7.896,00 E 4 ESTRELAS
- EXPORTAR TODOS OS DADOS COLETADOS PARA UM JSON E UM CSV
'''

