'''
PROPOSTA DO DESAFIO: UTILIZAR MULTIPLAS ABAS (DESAFIO 2 E DESAFIO 3), CADA UMA ACESSANDO UMA PÁGINA ESPECÍFICA. PRIMEIRAMENTE, A AUTOMAÇÃO DEVE ACESSAR A ABA REFERENTE AO DESAFIO 3 E 
CAPTURAR O NOME DO USUÁRIO QUE SERÁ PROCESSADO. EM SEGUIDA, DEVERÁ ACESSAR A ABA DO DESAFIO 2 E BUSCAR PELO NOME DO USUÁRIO. APÓS A PESQUISA, DEVE CAPTURAR TODOS OS DADOS DOS USUÁRIOS
RETORNADOS PELO SITE COM O NOME DE USUÁRIO E, POR FIM, DEVE ACESSAR NOVAMENTE A ABA DO DESAFIO 3 E PREENCHER OS DADOS CAPTURADOS CORRETAMENTE NO FORMULÁRIO, DE ACORDO COM A SUA CORRESPONDÊNCIA.
O PROCESSO DEVE SE REPETIR PARA TODOS OS USUÁRIOS FORNECIDOS PELA PÁGINA DA ABA DE DESAFIO 2 ATÉ QUE HAJA INDICAÇÃO DE QUE TODOS OS USUÁRIOS JÁ FORAM CAPTURADOS.
'''

from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from openpyxl import Workbook, load_workbook

driver = webdriver.Chrome()
driver.get('https://curso-web-scraping.pages.dev/#/desafio/3')
driver.maximize_window()